language: java
jdk:
  - oraclejdk8
branches:
  except:
    - /.*test$/
before_script: sudo apt-get install build-essential automake1.10 libtool
script: "mvn install -P linux64"

after_success:
  - mvn -P linux64 jacoco:report coveralls:report

after_failure:
  - cat lmdbjni-linux64/target/surefire-reports/*.txt
